hydra:
  output_subdir: null
  run:  
    dir: .
data:
  task: binary
  num_pos: 7
  num_neg: 5
para:
  num_events: 8
  gamma: 0.005
  alpha: 0.01
  beta: 0.01
  diversity_threshold: 0.03
  max_norm: 1.0
opt:
  name: Adam
  lr: 1e-4
  weight_decay: 5e-5
sche:
  name: SVFENDLR

num_epoch: 25
batch_size: 128
seed: 2024
model: SVFEND
dataset: FakeSV
type: default
patience: 8